### PR TITLE
Reworked the hosts module

### PR DESCRIPTION
**Pull request by Lazarus974**
Now watching the file only on master process to reduce file system accesses
Now using IPC for spawns to talk with master in order to keep hosts configuration synchronized
Now checking if an option named "hostsFile" is present in the root configuration to use that file instead of /etc/hosts

### CODE REVIEW

**Comment by Lazarus974** [comment]
Fix https://github.com/binarysec/gate/issues/37

**Comment by mykiimike** [comment]
Did you try your patch in runtime ? no problem to use /etc/hosts or another one ?

**Comment by mykiimike** [comment]
After the merge an update of https://github.com/binarysec/gate/wiki/Configuration is required

**Comment by mykiimike** [comment]
And this one https://github.com/binarysec/gate/blob/master/doc/references/root.ref

**Comment by Lazarus974** [comment]
The patch was only tested under local circumstances with default configuration. It worked for the forward proxy feature.

Documentation has been updated just now.

**Pull request merged**
